apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowdlaunch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cd-frontend
  template:
    metadata:
      labels:
        app: cd-frontend
    spec:
      containers:
      - name: cdfrontend-container
        image: donkolawolu/task-login-image
       
    
         
